### ISSUE TITLE
ContentBlockConfig not recognizing the endpoint property at buildtime

### ISSUE THREAD

**Issue by Ganonside** [crdschurch/crds-ng2-content-block#11]
When trying to use `ContentBlockConfig.forRoot` and passing in an object literal with an endpoint property, Typescript throws a compile error saying Object cannot be assigned to type ContentBlockConfig.

**Comment by tcmacdonald** [comment]
@Ganonside – What version of the package are you using?

`v0.2.0` adds support for object literals. The error message you're seeing suggests you might be on a previous version which expects an actual `ContentBlockConfig` object to be passed to `forRoot()`.

**Comment by Ganonside** [comment]
I am using v0.2.0

**Comment by Ganonside** [comment]
I made a pull request that fixed the issue for me and matt.

**Comment by tcmacdonald** [comment]
Closed via #13
