### ISSUE TITLE
Pulling this into an Angular CLI project results in error

### ISSUE THREAD

**Issue by silbermm** [crdschurch/crds-ng2-content-block#8]
The specific error is:
`ERROR in crds-angular-boilerplate/node_modules/crds-ng2-content-block/src/content-block/content.service.ts (25,21): Cannot find name 'process'.)`

My assumption is that project is trying to get the CMS_ENDPOINT from the environment, but each project may be accessing the environment variables differently. It would be nice if we can pass in the CMS_ENDPOINT when initializing the module.

**Comment by tcmacdonald** [comment]
@silbermm Your assumption is correct – the project assumes that env variable is accessible during build. I'll update the project per your suggestion soon.

**Comment by tcmacdonald** [comment]
This will be address in [US7443](https://rally1.rallydev.com/#/66096747656d/detail/userstory/101097836140?fdp=true).

**Comment by tcmacdonald** [comment]
Closed via #9
